### ISSUE TITLE
Recommendations for usage of SO3ExpCompactTransform vs SO3ExpBijectiveTransform

### ISSUE THREAD

**Issue by akashsengupta1997** [pimdh/relie#2]
Hi, sorry to bother you again!

I was wondering if you had any insights on the pros and cons of using SO3ExpCompactTransform vs SO3ExpBijectiveTransform for the exp map from so(3) to SO(3)?

The code makes it clear that SO3ExpCompactTransform assumes that the so(3) distribution has support in the <2pi ball, while SO3ExpBijectiveTransform assumes support in the <pi ball (i.e. where the exp map is injective). 

In your experiments code, you seem to set the support radius as 1.1pi or 1.6pi and use SO3ExpCompactTransform.

Are there any significant advantages (e.g. numerical accuracy / edge cases) to extending the support radius on so(3) beyond pi? If so, should I basically always use SO3ExpCompactTransform and use some support radius between pi and 2pi?

Thanks,
Akash

**Comment by pimdehaan-qc** [comment]
Hi,
If you restrict to the <pi ball, the exponential map is not surjective. A (measure zero) subset of SO(3) can not be reached. For example, if you want to model something like a uniform distribution on SO(3), you'll need the SO3ExpCompactTransform.
Pim

**Comment by akashsengupta1997** [comment]
ah okay makes sense, thanks!
