### ISSUE TITLE
Computation of log p(X|G) in VI

### ISSUE THREAD

**Issue by dilaragokay** [pimdh/relie#3]
I have some questions regarding the computation of `log p(X|G)` in [prediction_loss_fn](https://github.com/pimdh/relie/blob/d34ed58bcbd82335d29e9dfb2c6170dbd83fd18f/relie/experiments/vi/main.py#L76).

1. Why do you use L2 loss here? Would it be possible to use another loss instead of it?
2. I see no `log` operation in this function. Is there any other operation that substitutes it?

Thanks in advance!

**Comment by pimdh** [comment]
Hi Dilara,
The L2 loss corresponds to a log likelihood of a Gaussian distribution with
fixed (unit) variance - both are just the squared norm. This is quite
typically used as decoder distribution in VAE training. Feel free to
replace it with another distribution to your liking.
Hope that helps. Best wishes,
Pim

Op ma 4 apr. 2022 om 09:26 schreef Dilara Gokay ***@***.***>:

**Comment by dilaragokay** [comment]
Thanks, that makes sense!
