### ISSUE TITLE
Get NaN when requesting log_prob of mu

### ISSUE THREAD

**Issue by yd-yin** [pimdh/relie#6]
If I request the log_prob of mu, an assertion error will be raised indicating NaN.
```python
batch = 2
loc = torch.randn(batch, 3).double()
scale = F.softplus(torch.randn(batch, 3).double())
normal = Normal(torch.zeros_like(loc), scale)
transforms = [
    SO3ExpTransform(),
    SO3MultiplyTransform(so3_exp(loc))]
dist = LDTD(normal, transforms)

GT = so3_exp(loc)

loss = -dist.log_prob(GT)
```

It may come from https://github.com/pimdh/relie/blob/master/relie/utils/so3_tools.py#L143 where `x_norm` is zero

I'm not sure if simply adding a small eps to the norm would be fine, since xset of zero vector is a sphere while xset of a very tiny vector is not.

**Comment by pimdh** [comment]
Hi,

You're evaluating the density of SO3ExpTransform exactly as the identity -
as you translate by mu and evaluate at mu. This density is defined almost
everywhere, but not at the identity (and I think at a countable set of
spheres), which is fine theoretically, as that's a measure 0 set. It thus
makes sense for the code to crash - although a better error message might
have been better. If you evaluate the density close to the identity, you
should get a valid value.

Does that help?

Pim

Op do 9 jun. 2022 om 09:50 schreef Yin Yingda ***@***.***>:

**Comment by pimdh** [comment]
@lcfalors anything to add?

**Comment by pimdh** [comment]
Just to add, one can define a density throughout the manifold, by removing
the singularity <https://en.wikipedia.org/wiki/Removable_singularity> in
the equation we use to compute the density. Our density does have a proper
limit at the identity, which you can see by evaluating it very close to the
identity. That density defined everywhere would agree almost everywhere
with the one we implemented, so is in that sense equivalent.

Op do 9 jun. 2022 om 12:05 schreef Pim de Haan ***@***.***>:

**Comment by yd-yin** [comment]
Hi,
Thanks for your information. It helps a lot!

Then I think when training MLE with ReLie, it is ok to simply skip the instances that result in this NaN problem in one iteration, since their predictions are exactly the same as GTs and there is no need to update. Is that right?

Thanks

**Comment by pimdh** [comment]
That sounds like a good plan.

Op vr 10 jun. 2022 om 08:43 schreef Yin Yingda ***@***.***>:

**Comment by yd-yin** [comment]
Yeah, thank you
